# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import sql_pb2 as sql__pb2


class SQLStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteSQL = channel.unary_stream(
                '/distributed.SQL/ExecuteSQL',
                request_serializer=sql__pb2.SQLRequest.SerializeToString,
                response_deserializer=sql__pb2.Record.FromString,
                )


class SQLServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteSQL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SQLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteSQL': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteSQL,
                    request_deserializer=sql__pb2.SQLRequest.FromString,
                    response_serializer=sql__pb2.Record.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed.SQL', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SQL(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteSQL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/distributed.SQL/ExecuteSQL',
            sql__pb2.SQLRequest.SerializeToString,
            sql__pb2.Record.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
